"""empty message

Revision ID: cf53c394a7ec
Revises: b7776d9788d3
Create Date: 2020-01-12 19:01:56.643489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf53c394a7ec'
down_revision = 'b7776d9788d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f1date', sa.String(length=20), nullable=True),
    sa.Column('f1duration', sa.String(length=10), nullable=True),
    sa.Column('flavors', sa.String(length=200), nullable=True),
    sa.Column('f2date', sa.String(length=20), nullable=True),
    sa.Column('f2duration', sa.String(length=10), nullable=True),
    sa.Column('rating', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
